{{- if .Values.budget -}}
{{- if and .Values.budget.minAvailable .Values.budget.maxUnavailable -}}
{{- required "You can only set either minAvailable or maxUnavailable but not both." nil -}}
{{- end -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "pgbouncer.fullname" . }}
  labels:
    {{- include "pgbouncer.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "pgbouncer.selectorLabels" . | nindent 6 }}
  minAvailable: {{ .Values.budget.minAvailable }}
  maxUnavailable: {{ .Values.budget.maxUnavailable }}
{{- end -}}
