apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pgbouncer.fullname" . }}-config
  labels:
    {{- include "pgbouncer.labels" . | nindent 4 }}
type: Opaque
data:
  pgbouncer.ini: |-
    {{- include "pgbouncer.pgbouncer.ini" . | b64enc | nindent 4 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pgbouncer.fullname" . }}-userlist
  labels:
    {{- include "pgbouncer.labels" . | nindent 4 }}
type: Opaque
data:
  userlist.txt: |-
    {{- include "pgbouncer.userlist.txt" . | b64enc | nindent 4 }}
  {{- range $k, $v := .Values.users.userlist }}
  {{ $k }}: {{ $v | b64enc }}
  {{- end }}
