apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pgbouncer.fullname" . }}-secret
  labels:
    {{- include "pgbouncer.labels" . | nindent 4 }}
type: Opaque
data:
  userlist.txt: |-
    {{- include "pgbouncer.userlist.txt" . | b64enc | nindent 4 }}
  pgbouncer.ini: |-
    {{- include "pgbouncer.pgbouncer.ini" . | b64enc | nindent 4 }}
